name = "PassAll"
version = "0.1.0"
defaultTargets = ["PassAll"]

[leanOptions]
experimental.module = true

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.26.0"

[[lean_lib]]
name = "PassAll"
globs = ["PassAll.+"]
